name: CI Builds

on:
  pull_request:
  push:
    branches:
    - main
    paths:
    - '*'
    - '!/docs/*' # Don't run workflow when files are only in the /docs directory

jobs:
  nredisearch:
    name: NRediSearch (Ubuntu)
    runs-on: ubuntu-latest
    services:
      redisearch:
        image: redislabs/redisearch:latest
        ports:
          - 6385:6379
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Setup .NET Core 3.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Setup .NET 5.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: .NET Build
      run: dotnet build Build.csproj -c Release /p:CI=true
    - name: NRediSearch.Tests
      run: dotnet test tests/NRediSearch.Tests/NRediSearch.Tests.csproj -c Release --logger trx --results-directory ./test-results/ /p:CI=true
    - uses: dorny/test-reporter@v1
      continue-on-error: true
      if: success() || failure()
      with:
        name: NRediSearch.Tests - Results
        path: 'test-results/*.trx'
        reporter: dotnet-trx
    - name: .NET Lib Pack
      run: dotnet pack src/NRediSearch/NRediSearch.csproj --no-build -c Release /p:Packing=true /p:PackageOutputPath=%CD%\.nupkgs /p:CI=true